global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'crow-chat'

scrape_configs:

  # Backend app metrics
  - job_name: 'crow-chat-backend'
    static_configs:
      - targets: ['chat-backend:5000']
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
